version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - 6379:6379
  service:
    image: "ghcr.io/twobiers/software-architecture-sustainability-experiment:0.1-${VARIANT:-no-cache}"
    restart: unless-stopped
    ports:
      - 8081:8080
    deploy:
      replicas: 5
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MONGO_DATABASE=off
      - MONGO_COLLECTION=products
  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    deploy:
      replicas: 1
    depends_on:
      - service
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      replicas: 0
    command:
      - '--path.rootfs=/host'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.diskstats'
      - '--collector.filefd'
      - '--collector.filesystem'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.netdev'
      - '--collector.netstat'
      - '--collector.stat'
      - '--collector.interrupts'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
volumes:
  mongo-data: {}