services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=90d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    extra_hosts:
      - "pdu.local:192.168.178.78"
    ports:
      - 9116:9116
    command: --config.file=/etc/snmp_exporter/snmp.yml
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
