services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # If we want we can use the entrypoint to substitute environment variables in the config file
    # entrypoint: ["/bin/prometheus-init.sh"]
    command:
      - '--web.enable-admin-api'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
      - '--storage.tsdb.retention.time=90d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scripts/prometheus-init.sh:/bin/prometheus-init.sh
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    extra_hosts:
      - "pdu.local:192.168.178.78"
    ports:
      - 9116:9116
    command: --config.file=/etc/snmp_exporter/snmp.yml
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
