services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
  postgres:
    image: postgres:15.0-alpine
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  service:
    image: "ghcr.io/twobiers/software-architecture-sustainability-experiment:0.1-${VARIANT:-no-cache}"
    container_name: service
    restart: always
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MONGO_DATABASE=off
      - MONGO_COLLECTION=products
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DATABASE=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SCHEMA=demo
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    restart: always
    depends_on:
      - service
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
