services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=90d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
