global:
  scrape_interval: 1s 

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 60s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node
    static_configs:
    - targets: [ ] # TODO: Add DUT adress here
  - job_name: 'snmp'
    static_configs:
      - targets: [ ]  # TODO: Add PDU network address as target
    metrics_path: /snmp
    params:
      module: [if_mib] # TODO: Not sure what this does
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
